Google mail Service
Kwakyesamuelosei/employment-profiling-system pull request #15
Opened 2020-02-24 16:27 UTC by agyen

2020-02-24 16:58 UTC, sammoorhouse requested changes

2020-02-24 16:58 UTC, sammoorhouse commented on db/holiday.sql
> +INSERT INTO request_status(req_status) VALUES ('PENDING');
I think you should  explicitly insert request_status_id here, just in case someone comes along later and reorders these insertions :)

2020-02-24 16:58 UTC, sammoorhouse commented on src/main/java/io/turntabl/employementprofilingsystem/SendingMail/RequestMail.java
> +package io.turntabl.employementprofilingsystem.SendingMail;
I'm going to assume these are the same as for the pollstar service?

2020-02-25 11:50 UTC, sammoorhouse approved these changes

2020-02-25 11:50 UTC, sammoorhouse commented on db/holiday.sql
> +INSERT INTO request_status(request_status_id, req_status) VALUES (1, 'PENDING');
well donr

2020-02-25 12:06 UTC, agyen commented on db/holiday.sql
> +INSERT INTO request_status(request_status_id, req_status) VALUES (1, 'PENDING');
thanks!

2020-02-25 12:06 UTC, merged